name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - run: python -m pip install -U pip wheel
      - run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: if [ -d tests ]; then pip install pytest && pytest -q; else echo "no tests"; fi
